"""Create shortened_urls table

Revision ID: 2e751387bbf4
Revises: 330cdfb4240d
Create Date: 2025-03-14 18:09:19.798178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e751387bbf4'
down_revision: Union[str, None] = '330cdfb4240d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
