"""Add indices

Revision ID: 3dd5bb0700c7
Revises: 6a0c8cd7eedd
Create Date: 2025-03-16 17:36:43.528946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd5bb0700c7'
down_revision: Union[str, None] = '6a0c8cd7eedd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shortened_urls_clicks'), 'shortened_urls', ['clicks'], unique=False)
    op.create_index(op.f('ix_shortened_urls_original_url'), 'shortened_urls', ['original_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortened_urls_original_url'), table_name='shortened_urls')
    op.drop_index(op.f('ix_shortened_urls_clicks'), table_name='shortened_urls')
    # ### end Alembic commands ###
