"""Add project_name to shortened_urls

Revision ID: 6a0c8cd7eedd
Revises: 79cc06e8e692
Create Date: 2025-03-16 15:23:39.739514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0c8cd7eedd'
down_revision: Union[str, None] = '79cc06e8e692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortened_urls', sa.Column('project_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortened_urls', 'project_name')
    # ### end Alembic commands ###
