"""Добавлен expires_at для срока действия ссылок

Revision ID: 79cc06e8e692
Revises: c84139fb768b
Create Date: 2025-03-16 11:42:38.572146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79cc06e8e692'
down_revision: Union[str, None] = 'c84139fb768b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortened_urls', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortened_urls', 'expires_at')
    # ### end Alembic commands ###
