"""Add custom_alias to shortened_urls

Revision ID: c84139fb768b
Revises: 16e10784f3db
Create Date: 2025-03-15 13:05:48.223878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84139fb768b'
down_revision: Union[str, None] = '16e10784f3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortened_urls', sa.Column('custom_alias', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'shortened_urls', ['custom_alias'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shortened_urls', type_='unique')
    op.drop_column('shortened_urls', 'custom_alias')
    # ### end Alembic commands ###
